accounts/urls.py
from django.urls import path, reverse_lazy

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.log_in, name='log_in'),
    path('logout/', views.log_out, name='log_out'),
    path('register/', views.register_user, name='register_user')

]

lyriclicking/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views import static
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from accounts.forms import ResetPasswordForm, PasswordSetForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lyriclicker/', include('lyriclicker.urls')),
    path('lyrics/', include('lyrics.urls')),
    path('accounts/', include('accounts.urls')),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(
             form_class=ResetPasswordForm,
             template_name='resetpassword.html'),
         name='reset_password'),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='passwordsent.html'),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             form_class=PasswordSetForm,
             template_name='setpassword.html'),
         name="password_reset_confirm"),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='passwordset.html'),
         name="password_reset_complete"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lyrics/urls.py
from django.urls import path

from . import views

app_name = 'lyrics'
urlpatterns = [
    path('lick/', views.lick_lyric, name='lick_lyric'),
    path('delete/', views.delete_line, name='delete_line'),
    path('setendpoint/', views.set_endpoint, name='set_endpoint'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Load bootstrap 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha256-L/W5Wfqfa0sdBNIKN9cG6QA5F2qx4qICmU2VgLruv9Y=" crossorigin="anonymous" />
        -->
    <!-- Load Font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css"
        integrity="sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ=" crossorigin="anonymous" />
    <!-- Load Jquery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <!-- Load popperJS 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"
        integrity="sha256-/ijcOLwFf26xEYAjW75FizKVo5tnTYiQddPZoLUHHZ8=" crossorigin="anonymous"></script>
        -->
    <!-- Load Bootstrap 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha256-WqU1JavFxSAMcLP2WIOI+GB2zWmShMI82mTpLDcqFUg=" crossorigin="anonymous"></script>
        -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/4.1.0/wavesurfer.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/4.1.0/plugin/wavesurfer.timeline.min.js"></script>
    <!-- Load Favicon -->
    <link rel="icon" type="image/png" href="assets/images/boembep.ico" />
    <!-- Load Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
</head>

<body>

    <header>
        <a href="/" title="Lyriclicking">
            <div class="er-logo">
                LyriCLicking
            </div>
        </a>
        <nav class="er-header">
            <!-- Header / desktop menu -->


            <div class="er-menu-item" id="er-menu-account">
                NEW RHYME
            </div>
            <a href="/" title="Lyric licker">
                <div class="er-menu-item" id="er-menu-new">
                    LYRIC LICKER
                </div>
            </a>
            <a href="{% url 'accounts:register_user' %}?next={{ request.path|urlencode }}" title="Create account">
                <div class="er-menu-item" id="er-menu-account">
                    REGISTER
                </div>
            </a>
            <a href="{% url 'accounts:log_in' %}?next={{ request.path|urlencode }}" title="Log in to use the shop">
                <div class="er-menu-item" id="er-menu-logout">

                    LOGIN

                </div>
            </a>
            <a href="{% url 'accounts:log_out' %}?next={{ request.path|urlencode }}" title="Log in to use the shop">
                <div class="er-menu-item" id="er-menu-logout">

                    LOGOUT

                </div>
            </a>
            <div>

            </div>
        </nav>
    </header>

    <section class="er-screen">
        <!-- Black row for current lyric background -->
        <div class="er-lyrics-gradient">
        </div>
        <!-- Templates content -->
        {% block content %} {% endblock %}

    </section>

</body>

</html>

templates/passwordsent.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Password reset notification -->

<div class="er-wrap">
    <h1>Your password has been reset</h1>
</div>

<div class="er-info-wrap">
    <p>
        We have sent you a link to change your password.
    </p>
</div>


{% endblock %}

templates/passwordset.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- New password set notification -->

<div class="er-wrap">
    <h1>Your password has been changed</h1>
</div>

<div class="er-info-wrap">
    <p>
        Your password has successfully been changed.
    </p>
</div>


{% endblock %}

templates/resetpassword.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<!-- Password reset form -->

<div class="er-form-wrap">
    <p class="text-left">
        <a class="" href="{% url 'accounts:log_in' %}?next={{ next }}" title="Goto login page">
            <i class="fas fa-sign-in-alt"></i> Got here by mistake? Please log-in here
        </a>
    </p>
    <form class="form-horizontal" method="post">
        <input type="hidden" name="next" value="{{ next }}">
        {% crispy form form.helper %}
    </form>
    <p>
        <a class="" href="{% url 'accounts:register_user' %}?next={{ next }}" title="Register as a new customer">
            Don't have an account? Please register here <i class="fas fa-user-plus"></i>
        </a>
    </p>
</div>


{% endblock %}

templates/setpassword.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


<!-- Enter new password form -->

<div class="er-form-wrap">
    <form class="form-horizontal" method="post">
        <input type="hidden" name="next" value="{{ next }}">
        {% crispy form form.helper %}
    </form>

</div>


{% endblock %}